version: '3'
services:
  db:
    image: postgres:15-alpine
    container_name: db
    volumes:
     - ./data/db:/var/lib/postgresql/data/
    env_file:
      - .env.sample

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    expose:
      - 6379

  app:
    build: .
    container_name: app
    env_file:
      - .env.sample
    command: >
      bash -c "python manage.py migrate
      && python3 manage.py collectstatic
      && python manage.py csu
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    container_name: celery_worker
    env_file:
      - .env.sample
    depends_on:
      - redis
      - app
    command: celery -A config worker -l INFO

  celery_beat:
    build: .
    container_name: celery_beat
    env_file:
      - .env.sample
    depends_on:
      - celery_worker
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler